workspace:
  base: /go
  path: src/github.com/uphy/drone-ansible

pipeline:
  test:
    image: golang:1.9
    environment:
      - CGO_ENABLED=0
    commands:
      - go test -cover -coverprofile=coverage.out    
      - go test -cover -coverprofile=coverage.out plugin/*

  publish:
    image: plugins/docker
    repo: uphy/drone-ansible:2
    secrets: [ docker_username, docker_password ]
    when:
      branch: master
      event: push
